version: "3.9"

networks:
  backend:
    driver: bridge

services:
  # app:
  #   container_name: app_container
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #     - DATABASE_HOST=${DB_HOST}
  #     - DATABASE_PORT=${DB_PORT}
  #     - TEST_POSTGRES_USER=${TEST_DB_USER}
  #     - TEST_POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
  #     - TEST_POSTGRES_DB=${TEST_DB_NAME}
  #     - TEST_DATABASE_HOST=${TEST_DB_HOST}
  #     - TEST_DATABASE_PORT=${TEST_DB_PORT}
  #   tty: true
  #   build: .
  #   ports:
  #     - 8000:8080
  #   restart: on-failure
  #   depends_on:
  #     - db:
  #         condition: service_healthy
  #   networks:
  #     - backend

  db:
    image: postgres:15.3
    container_name: db_container
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users"]
      interval: 10s
      timeout: 5s
      retries: 5

